# Generated by Django 5.0.4 on 2024-05-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tk', '0002_bucketlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BucketListItem',
        ),
    ]
